# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', height_field=95, upload_to='post', width_field=95),
        ),
    ]
